spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${github-client-id}
            client-secret: ${github-client-secret}
          facebook:
            client-id: ${facebook-client-id}
            client-secret: ${facebook-client-secret}
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
          okta:
            client-name: Okta
            client-id: ${okta-client-id}
            client-secret: ${okta-client-secret}
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/okta

        provider:
          okta:
            authorization-uri: https://dev-275566.okta.com/oauth2/default/v1/authorize
            token-uri: https://dev-275566.okta.com/oauth2/default/v1/token
            user-info-uri: https://dev-275566.okta.com/oauth2/default/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://dev-275566.okta.com/oauth2/default/v1/keys




